# Generated by Django 5.1.1 on 2024-10-15 09:27

import django.db.models.deletion
import django_jalali.db.models
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', mdeditor.fields.MDTextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='شناسه')),
                ('schedule_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ برگذاری')),
                ('register_deadline', django_jalali.db.models.jDateField(verbose_name='تاریخ مهلت ثبت\u200cنام')),
                ('location', models.CharField(default='سالن همایش قاسم سلیمانی', max_length=200, verbose_name='مکان برگذاری')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت رخداد')),
            ],
            options={
                'verbose_name': 'رخداد',
                'verbose_name_plural': 'رخداد ها',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events_images/', verbose_name='عکس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event', verbose_name='رخداد')),
            ],
            options={
                'verbose_name': 'عکس رخداد',
                'verbose_name_plural': 'عکس های رخداد',
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('fname', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('student_number', models.CharField(max_length=20, verbose_name='شماره دانشجویی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to='events.event', verbose_name='رخداد')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده',
                'verbose_name_plural': 'شرکت\u200cکننده ها',
                'unique_together': {('event', 'email')},
            },
        ),
    ]
