# Generated by Django 5.1.1 on 2024-10-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventuser_created_at_eventuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together={('event', 'email')},
        ),
    ]
