# Generated by Django 5.1.1 on 2024-10-08 14:40

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='description'),
        ),
    ]
