# Generated by Django 5.1.1 on 2024-10-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'فعالیت دانشگاهی',
                'verbose_name_plural': 'فعالیت های دانشگاهی',
            },
        ),
        migrations.CreateModel(
            name='EducationalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('date', models.DateField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('related_link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'لینک خارجی',
                'verbose_name_plural': 'لینک های خارجی',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('date', models.DateField(verbose_name='تاریخ انتشار')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'حوزه تحقیق',
                'verbose_name_plural': 'حوزه\u200cهای تحقیقاتی',
            },
        ),
        migrations.CreateModel(
            name='TeachingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('semester', models.CharField(blank=True, max_length=300, null=True, verbose_name='ترم درسی')),
            ],
            options={
                'verbose_name': 'درس تدریسی',
                'verbose_name_plural': 'دروس تدریسی',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('from_date', models.DateField(verbose_name='تاریخ شروع')),
                ('to_date', models.DateField(verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('fname', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('position', models.CharField(max_length=100, verbose_name='سمت کاری')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل کار')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('profile_image', models.ImageField(default='staff/profiles/default.svg', upload_to='staff/profiles', verbose_name='عکس')),
                ('academic_activities', models.ManyToManyField(blank=True, to='professor_staff.academicactivity', verbose_name='فعالیت های دانشگاهی')),
                ('educational_records', models.ManyToManyField(blank=True, to='professor_staff.educationalrecord', verbose_name='سوابق تحصیلی')),
                ('external_links', models.ManyToManyField(blank=True, to='professor_staff.externallink', verbose_name='لینک های خارجی')),
                ('papers', models.ManyToManyField(blank=True, to='professor_staff.paper', verbose_name='مقالات')),
                ('teaching_courses', models.ManyToManyField(blank=True, to='professor_staff.teachingcourse', verbose_name='دروس تدریسی')),
                ('work_experiences', models.ManyToManyField(blank=True, to='professor_staff.workexperience', verbose_name='سوابق کاری')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('fname', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت کاری')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل کار')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('profile_image', models.ImageField(default='professors/profiles/default.svg', upload_to='professors/profiles', verbose_name='عکس')),
                ('academic_activities', models.ManyToManyField(blank=True, to='professor_staff.academicactivity', verbose_name='فعالیت های دانشگاهی')),
                ('educational_records', models.ManyToManyField(blank=True, to='professor_staff.educationalrecord', verbose_name='سوابق تحصیلی')),
                ('external_links', models.ManyToManyField(blank=True, to='professor_staff.externallink', verbose_name='لینک های خارجی')),
                ('papers', models.ManyToManyField(blank=True, to='professor_staff.paper', verbose_name='مقالات')),
                ('research_areas', models.ManyToManyField(blank=True, to='professor_staff.researcharea', verbose_name='حوزه\u200cهای تحقیقاتی')),
                ('teaching_courses', models.ManyToManyField(blank=True, to='professor_staff.teachingcourse', verbose_name='دروس تدریسی')),
                ('work_experiences', models.ManyToManyField(blank=True, to='professor_staff.workexperience', verbose_name='سوابق کاری')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
    ]
