# Generated by Django 5.1.1 on 2024-10-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='شناسه'),
        ),
        migrations.AddField(
            model_name='professor',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تگ کاری'),
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='شناسه'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تگ کاری'),
        ),
    ]
