# Generated by Django 5.1.1 on 2024-10-15 09:27

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shahid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('martyrdom_location', models.CharField(max_length=200, verbose_name='محل شهادت')),
                ('martyrdom_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شهادت')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('birth_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='محل تولد')),
                ('life_story', models.TextField(blank=True, null=True, verbose_name='زندگی\u200cنامه')),
                ('will', models.TextField(blank=True, null=True, verbose_name='وصیت\u200cنامه')),
                ('profile_image', models.ImageField(default='shohada/profiles/default.svg', upload_to='shohada/profiles', verbose_name='عکس پروفایل')),
                ('important_quotes', models.TextField(blank=True, null=True, verbose_name='نقل\u200cقول\u200cهای مهم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='شناسه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
            ],
            options={
                'verbose_name': 'شهید',
                'verbose_name_plural': 'شهدا',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shohada_images', verbose_name='عکس')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shahid.shahid', verbose_name='شهید')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس\u200cها',
            },
        ),
    ]
