# Generated by Django 5.1.1 on 2024-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shahid',
            name='description',
        ),
        migrations.AddField(
            model_name='shahid',
            name='life_story',
            field=models.TextField(blank=True, null=True, verbose_name='زندگی\u200cنامه'),
        ),
    ]
