# Generated by Django 5.1.1 on 2024-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='profile_image',
            field=models.ImageField(default='association/logos/default.svg', upload_to='association/logos', verbose_name='لوگو انجمن'),
        ),
    ]
